### ISSUE TITLE
Connectors - Rename orchestrator and organize default profiles

### ISSUE THREAD

**Issue by olivierdupuis** [discursus-data/damn#26]
Current way of configuring orchestrator in `connectors.yml` file is the following...

```
dagster:
  prod:
    endpoint: https://xyz.dagster.cloud/prod/graphql
    api_token: user:abc123
  local:
    endpoint: http://127.0.0.1:3000/graphql
    api_token: 
```

But that is bound to change as we want to focus on connectors as roles and not service provides. So first goal is really to rename `dagster` to `orchestrator` and have profiles such as `dagster_prod` and `dagster_local` for example.

That means that we need to revisit defaults. For now, we are fetching a profile named `prod` for the `dagster` connector. But we might want to revisit that default. Instead, we could either have the first profile as the default, or configure a profile as default in the `yml` file.
